[2025-09-05T11:11:28.739+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-05T11:11:28.766+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_pipeline.convert_amount scheduled__2025-09-04T09:00:00+00:00 [queued]>
[2025-09-05T11:11:28.778+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_pipeline.convert_amount scheduled__2025-09-04T09:00:00+00:00 [queued]>
[2025-09-05T11:11:28.779+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-09-05T11:11:28.809+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): convert_amount> on 2025-09-04 09:00:00+00:00
[2025-09-05T11:11:28.820+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-05T11:11:28.823+0000] {standard_task_runner.py:63} INFO - Started process 1567 to run task
[2025-09-05T11:11:28.823+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'currency_exchange_pipeline', 'convert_amount', 'scheduled__2025-09-04T09:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_pipeline.py', '--cfg-path', '/tmp/tmp0pzuwewp']
[2025-09-05T11:11:28.827+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask convert_amount
[2025-09-05T11:11:28.909+0000] {task_command.py:426} INFO - Running <TaskInstance: currency_exchange_pipeline.convert_amount scheduled__2025-09-04T09:00:00+00:00 [running]> on host 89d397d7ed3a
[2025-09-05T11:11:29.021+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_exchange_pipeline' AIRFLOW_CTX_TASK_ID='convert_amount' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-04T09:00:00+00:00'
[2025-09-05T11:11:29.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-05T11:11:29.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-05T11:11:29.036+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/currency_exchange_pipeline.py", line 13, in convert_amount
    conversions = {currency: usd_amount * rate for currency, rate in rates.items()}
                                                                     ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
[2025-09-05T11:11:29.060+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=currency_exchange_pipeline, task_id=convert_amount, execution_date=20250904T090000, start_date=20250905T111128, end_date=20250905T111129
[2025-09-05T11:11:29.084+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task convert_amount ('NoneType' object has no attribute 'items'; 1567)
[2025-09-05T11:11:29.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-05T11:11:29.151+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T11:11:29.156+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
